
version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: library-backend
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: library-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres-data:
